### ISSUE TITLE
GET http://localhost:4000/ 404 (Not Found)

### ISSUE THREAD

**Issue by kyozbladex** [ShankyTiwari/Real-time-private-chatting-app-using-React-Nodejs-mongodb-and-Socket.io#2]
Hi, i copy/paste this proyecto to check if it what i need for a personal proyect, but when i npm-start this, i always get this on the browser:

{"error":true,"message":"You are at wrong place. Shhoooo..."}

checking the code, it looks that it cant find the route, but i'm lost here, it's a clean copy-paste, why it fails?

on the browser console it keeps displaying "GET http://localhost:4000/ 404 (Not Found)"

any ideas??

**Comment by ShankyTiwari** [comment]
You must  be running Nodejs API code, you have to run React code as well. Thanks

**Comment by kyozbladex** [comment]
Hi, thanks for response, yes thats what i did, i copy/paste both proyects and run them, i just post this localhost problem thinking it was the reason why i did´t work, but on the front end it doesnt work neither, it keeps saying:

![image](https://user-images.githubusercontent.com/72166766/99975928-334e6300-2d79-11eb-845c-f766765caa48.png)

it only shows "user already taken" no matter what i put there, on the devs console it display that error, so i think its on the server side, thats why i posted this.
